site_name: MetaMorph Standalone
theme: readthedocs
nav:
  - Home: index.md
  - QuickStart             : quickstart.md
  - installation           : installation.md
  - Architecture           : architecture.md
  - References             : references.md

